### ISSUE TITLE
Build fails on 10.14 - Could NOT find OpenGL

### ISSUE THREAD

**Issue by kezorm** [KiCad/kicad-mac-builder#278]
Build fails on 10.14 - "Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR)".  CMake Error info shown below.  

Solution found at https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja

Specifically, following command was called
`installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

It seems the above is a short-term workaround, but that proper place for a long-term fix is in FindOpenGL.cmake?  When looking at above link, be sure to expand all answers as some of the most interesting comments were collapsed.

-----------------------------------------

CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindOpenGL.cmake:397 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:551 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/greg/KiCadProjects/KiCad/source/kicad-mac-builder/build/kicad/src/kicad-build/CMakeFiles/CMakeOutput.log".
See also "/Users/greg/KiCadProjects/KiCad/source/kicad-mac-builder/build/kicad/src/kicad-build/CMakeFiles/CMakeError.log".
make[2]: *** [kicad/src/kicad-stamp/kicad-configure] Error 1
make[1]: *** [CMakeFiles/kicad.dir/all] Error 2
make: *** [all] Error 2
Error while running make after rebuilding with a single job. Please report this issue if you cannot fix it after reading the README.
build.py argument summary:
build_type: Debug
docs_tarball_url: http://docs.kicad-pcb.org/kicad-doc-HEAD.tar.gz
extra_version: None
footprints_ref: origin/master
jobs: 1
kicad_ref: origin/master
macos_min_version: 10.14
packages3d_ref: origin/master
release: False
release_name: None
retry_failed_build: True
symbols_ref: origin/master
target: []
templates_ref: origin/master
translations_ref: origin/master
Traceback (most recent call last):
  File "./build.py", line 223, in <module>
    main()
  File "./build.py", line 219, in main
    build(parsed_args)
  File "./build.py", line 191, in build
    subprocess.check_call(make_command, env=dict(os.environ, PATH=new_path))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j1']' returned non-zero exit status 2

**Comment by adamwolf** [comment]
Thank you for the bug report!
